---
# tasks file for strongswan

- include: debian.yml
  when:
    ansible_os_family == "Debian"

- include: redhat.yml
  when:
    ansible_os_family == "RedHat"

- include: plugin.yml
  loop: "{{ plugins }}"
  loop_control:
    loop_var: plugin

- include: config.yml
  vars:
    connection: "{{ item }}"
  loop: "{{ strongswan_conn }}"
  loop_control:
    loop_var: conn

- include: service.yml
- include: firewall.yml
